# Generated by Django 6.1 on 2026-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_technology_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
