# Generated by Django 6.1 on 2026-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='detailed_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AddField(
            model_name='technology',
            name='detailed_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
