# Generated by Django 6.1 on 2026-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_text', models.CharField(blank=True, default='✦', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='agencysettings',
            options={'verbose_name': 'Agency Settings', 'verbose_name_plural': 'Agency Settings'},
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='commitment',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='cta_button',
            field=models.CharField(default='Start a Project →', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='cta_description',
            field=models.TextField(blank=True, default="Let's build something useful, modern and memorable."),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='cta_title',
            field=models.CharField(default='Ready to Grow Your Business?', max_length=200),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='footer_text',
            field=models.CharField(default='All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_badge',
            field=models.CharField(default='We build digital experiences', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_description',
            field=models.TextField(blank=True, default='We create modern websites, web applications and digital experiences.'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_highlight',
            field=models.CharField(default='We Grow Your Business.', max_length=200),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='agency/hero/'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_primary_text',
            field=models.CharField(default='Explore Services →', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_secondary_text',
            field=models.CharField(default='View Projects', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='hero_title',
            field=models.CharField(default='We Design. We Develop.', max_length=200),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='landing_badge',
            field=models.CharField(default='Our specialty', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='landing_button',
            field=models.CharField(default='Explore Landing Pages →', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='landing_description',
            field=models.TextField(blank=True, default='Create reusable, responsive campaign pages without rebuilding every page.'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='landing_title',
            field=models.CharField(default='Build once. Create unlimited landing pages.', max_length=200),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='projects_badge',
            field=models.CharField(default='Our work', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='projects_description',
            field=models.TextField(blank=True, default='Selected work from our agency portfolio.'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='projects_title',
            field=models.CharField(default='Featured Projects', max_length=150),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='services_badge',
            field=models.CharField(default='What we do', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='services_description',
            field=models.TextField(blank=True, default='Digital solutions designed around your business goals.'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=150),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='team_badge',
            field=models.CharField(default='Our experts', max_length=100),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='team_description',
            field=models.TextField(blank=True, default='Our developers build modern digital experiences.'),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='team_title',
            field=models.CharField(default='Meet Our Developers', max_length=150),
        ),
        migrations.AlterField(
            model_name='agencysettings',
            name='agency_name',
            field=models.CharField(default='My Agency', max_length=150),
        ),
    ]
