# Generated by Django 6.1 on 2026-08-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_alter_agencysettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='cta_button',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='landing_badge',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='landing_button',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='landing_description',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='landing_title',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='services_badge',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='services_description',
        ),
        migrations.RemoveField(
            model_name='agencysettings',
            name='services_title',
        ),
    ]
