# Generated by Django 6.1 on 2026-08-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
