# Generated by Django 6.1 on 2026-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='developers/cv/'),
        ),
    ]
